
DESCRIPTION = 'Another webscrapper software'
DEFAULT_TEXT_WIDTH = 80
ANCHOR_TAG = 'h1'
ANCHOR_DEEPNESS = 3
GRAPH_UP_COUNT = 3
MIN_PARAGRAPH_COUNT = 2
TEXT_WRAPPER_TAG = 'p'
BS_TAG = "<class 'bs4.element.Tag'>"
